config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  resources :users, except: [:new]
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  # "resources :articles" provides REST-ful routes to Rails resources (including index, show, edit, create, new, update (post & patch), destroy)

  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	validates :title, presence: true, length: {minimum: 6, maximum: 100}
	validates :description, presence: true, length: {minimum: 10, maximum: 300}

	# ":user" must be singular for this to work, not ":users"
	# in rails 5 and onwards, having a 'belongs_to' association
	# automatically makes that reference required.
	# So an article must have a user.
	# It can be made optional with "belongs_to :user, optional: true"
	belongs_to :user

	has_many :article_categories
	has_many :categories, through: :article_categories
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
	belongs_to :article
	belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
	validates :name, presence: true, uniqueness: true, length: {minimum: 2, maximum: 25}

	has_many :article_categories
	has_many :articles, through: :article_categories
end

app/models/user.rb
class User < ApplicationRecord
	# This can alternatively be done in a "do" block, if there's more to be done and need several lines
	before_save { self.email = email.downcase }

	validates :username, presence: true,
		uniqueness: { case_sensitive: false },
		length: {minimum: 3, maximum: 25}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true,
		uniqueness: { case_sensitive: false },
		length: {maximum: 105}, format: {with: VALID_EMAIL_REGEX}

	has_many :articles, dependent: :destroy
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	helper_method :current_user, :logged_in? # makes these methods available to the views
	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def logged_in?
		!!current_user
	end

	def require_user
		if !logged_in?
			flash[:alert] = "You must be logged in to perform that action"
			redirect_to login_path
		end
	end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	# the following line causes the "set_article" method to be run before the mentioned actions
	# it seemingly sets the @article instance variable within the scope of those methods / actions
	before_action :set_article, only: [:show, :edit, :update, :destroy]
	before_action :require_user, except: [:show, :index]
	before_action :require_same_user, only: [:edit, :update, :destroy]

	def show
		# byebug # used to stop execution and debug within the server console
	end

	def index
		@articles = Article.paginate(page: params[:page], per_page: 5)
	end

	def new
		@article = Article.new
	end

	def edit
	end

	def create
		# render plain: params[:article] # this can be used to plainly render this value back on the page, as another debugging tool
		@article = Article.new(article_params)
		@article.user = current_user
		# render plain: @article.inspect
		if @article.save
			# use a flash helper with a message
			flash[:notice] = "Article was created successfully."
			# redirect_to article_path(@article)
			# as an alternative shorthand, you can do the following and rails will know to redirect to that article
			redirect_to @article
		else
			render 'new' # re-renders the 'new' form, but now the article instance variable will have errors to display
		end
	end

	def update
		if @article.update(article_params)
			flash[:notice] = "Article was updated successfully."
			redirect_to @article
		else
			render 'edit' # re-renders the 'edit' form, but now the article instance variable will have errors to display
		end
	end

	def destroy
		@article.destroy
		redirect_to articles_path
	end

	private

	def set_article
		@article = Article.find(params[:id])
	end

	def article_params
		params.require(:article).permit(:title, :description, category_ids: [])
	end

	def require_same_user
		if current_user != @article.user && !current_user.admin?
			flash[:alert] = "You can only edit or delete your own article"
			redirect_to article_path @article
		end
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :require_admin, except: [:index, :show]

	def index
		@categories = Category.paginate(page: params[:page], per_page: 5)
	end

	def show
		@category = Category.find(params[:id])
		@articles = @category.articles.paginate(page: params[:page], per_page: 5)
	end

	def new
		@category = Category.new
	end

	def create
		@category = Category.new(category_params)
		if @category.save
			flash[:notice] = "Category was successfully created"
			redirect_to @category
		else
			render 'new'
		end
	end

	private

	def category_params
		params.require(:category).permit(:name)
	end

	def require_admin
		if !logged_in? || !current_user.admin?
			flash[:alert] = "Only admins can perform that action"
			redirect_to categories_path
		end
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
		redirect_to articles_path if logged_in?
	end

	def about
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			session[:user_id] = user.id
			flash[:notice] = "Logged in successfully"
			redirect_to user
		else
			flash.now[:alert] = "Incorrect username or password"
			render 'new'
		end
	end

	def destroy
		session[:user_id] = nil
		flash[:notice] = "Logged out"
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:show, :edit, :update, :destroy]
	before_action :require_user, only: [:edit, :update, :destroy]
	before_action :require_same_user, only: [:edit, :update, :destroy]

	def show
		@articles = @user.articles.paginate(page: params[:page], per_page: 5)
	end

	def index
		@users = User.paginate(page: params[:page], per_page: 5)
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			flash[:notice] = "Welcome to the Alpha Blog #{@user.username}, you have successfully signed up"
			redirect_to articles_path
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @user.update(user_params)
			flash[:notice] = "Your account information was successfully updated"
			redirect_to @user
		else
			render 'edit'
		end
	end

	def destroy
		@user.destroy
		session[:user_id] = nil unless current_user.admin? && @user != current_user
		flash[:notice] = "Account and all associated articles successfully deleted"
		redirect_to root_path
	end

	private

	def user_params
		params.require(:user).permit(:username, :email, :password)
	end

	def set_user
		@user = User.find(params[:id])
	end

	def require_same_user
		if @user != current_user && !current_user.admin?
			flash[:alert] = "You can only edit or delete your own account"
			redirect_to user_path @user
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def gravatar_for(user, options = {size: 80})
		email_address = user.email.downcase
		hash = Digest::MD5.hexdigest(email_address)
		gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{options[:size]}"
		image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/articles/_article_card.html.erb
<div class="row justify-content-md-center">
	<div class="col-8 pb-4">
		<div class="card text-center shadow mb-5 bg-white rounded">
			<div class="card-header fst-italic">
				<% if article.user %>
					by <%= link_to article.user.username, article.user, class: "text-underline-hover" %>
				<% end %>
				<% if article.categories.any? %>
							<div class="mt-2">
								<%= render article.categories %>
							</div>
						<% end %>
			</div>
			<div class="card-body">
				<h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success text-underline-hover"%></h5>
				<p class="card-text"><%= truncate(article.description, length: 100) %></p>
				<%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
				<% if logged_in? && (article.user == current_user || current_user.admin?) %>
					<%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info" %>
					<%= link_to "Delete", article_path(article), method: "delete", data: { confirm: "Are you sure you want to delete this article?" }, class: "btn btn-outline-danger" %>
				<% end %>
			</div>
			<div class="card-footer text-muted">
				<small>Created <%= time_ago_in_words(article.created_at) %> ago,
				edited <%= time_ago_in_words(article.updated_at) %> ago</small>
			</div>
		</div>
	</div>
</div>

app/views/articles/_form.html.erb
<div class="container">
	<div class="row justify-content-center">
		<div class="col-10">
			<%= render 'shared/errors', obj: @article %>
			<%= form_with(model: @article, class: "shadow p-3 mb-4 bg-info rounded", local: true) do |f| %>
				<div class="form-group row">
					<%= f.label :title, class: "col-sm-2 mb-3 col-form-label text-light" %>
					<div class="col-sm-10">
						<%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title of article" %>
					</div>
				</div>
				<div class="form-group row mb-3">
					<%= f.label :description, class: "col-sm-2 mb-3 col-form-label text-light" %>
					<div class="col-sm-10">
						<%= f.text_area :description, rows: 10, class: "form-control shadow rounded", placeholder: "Description" %>
					</div>
				</div>
				<div class="form-group row mb-3">
					<%= f.label :categories, class: "col-sm-2 mb-3 col-form-label text-light" %>
					<div class="col-sm-10">
						<%= f.collection_select :category_ids, Category.all, :id, :name, { include_blank: "Select categories" }, { multiple: true, size: 5, class: "form-select shadow rounded" } %>
					</div>
				</div>
				<div class="form-group row">
					<div class="col-sm-12 text-center">
						<%= f.submit class: "btn btn-outline-light btn-lg" %>
					</div>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/articles/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
</head>
<body>
	<h1 class="text-center pt-4 pb-4">Edit article</h1>

	<%= render 'form' %> <!-- unlike the application.html.erb file, we do not need to specify the folder name here (i.e. 'articles/form') -->

	<div class="container text-center pb-3">
		<%= link_to 'Cancel', article_path(@article), class: "text-info" %>
	</div>
</body>
</html>

app/views/articles/index.html.erb
<h1 class="text-center pt-4 pb-4">Listing all articles</h1>
<div class="container pb-4">
	<div class="flickr_pagination mb-4">
		<%= will_paginate @articles, :container => false %>
	</div>
	<% @articles.each do |article| %>
		<%= render 'article_card', article: article %>
	<% end %>
	<div class="flickr_pagination">
		<%= will_paginate @articles, :container => false %>
	</div>
</div>

app/views/articles/new.html.erb
<h1 class="text-center pt-4 pb-4">Create a new article</h1>

<%= render 'form' %> <!-- unlike the application.html.erb file, we do not need to specify the folder name here (i.e. 'articles/form') -->

<div class="container text-center pb-3">
	<%= link_to 'Cancel', articles_path, class: "text-info" %>
</div>

app/views/articles/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
</head>
<body>
	<h1 class="text-center pt-4 pb-4"><%= @article.title %></h1>
	<div class="container pb4">
		<div class="row justify-content-md-center">
			<div class="col-8 pb-4">
				<div class="card text-center shadow mb-5 bg-white rounded">
					<div class="card-header fst-italic">
						by <%= @article.user.username %>
						<%= link_to gravatar_for(@article.user, size: 81), user_path(@article.user) %>
						<% if @article.categories.any? %>
							<div class="mt-2">
								<%= render @article.categories %>
							</div>
						<% end %>
					</div>
					<div class="card-body">
						<div class="card-text text-start"><%= simple_format(@article.description) %></div>
						<% if logged_in? && (@article.user == current_user || current_user.admin?) %>
							<%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-info" %>
							<%= link_to "Delete", article_path(@article), method: "delete", data: { confirm: "Are you sure you want to delete this article?" }, class: "btn btn-outline-danger" %>
						<% end %>
					</div>
					<div class="card-footer text-muted">
						<small>Created <%= time_ago_in_words(@article.created_at) %> ago,
						edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
					</div>
				</div>
			</div>
		</div>
	</div>
</body>
</html>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class: "badge rounded-pill bg-info no-underline mx-1" %>

app/views/categories/index.html.erb
<h1 class="text-center pt-4 pb-4">Categories</h1>

<div class="flickr_pagination mb-4">
	<%= will_paginate @categories, :container => false %>
</div>

<% @categories.each do |category| %>
	<div class="row justify-content-md-center">
		<div class="col-4 pb-4">
			<div class="card text-center shadow mb-5 bg-white rounded">
				<div class="card-body">
					<h5 class="card-title"><%= link_to category.name, category_path(category), class: "text-success text-underline-hover"%></h5>
					<p class="card-text"><%= pluralize(category.articles.length, "article") %></p>
				</div>
				<div class="card-footer text-muted">
					<small>Created <%= time_ago_in_words(category.created_at) %> ago,
					edited <%= time_ago_in_words(category.updated_at) %> ago</small>
				</div>
			</div>
		</div>
	</div>
<% end %>

<div class="flickr_pagination">
	<%= will_paginate @categories, :container => false %>
</div>

app/views/categories/new.html.erb
<h1 class="text-center pt-4 pb-4">Create a new category</h1>

<div class="container">
	<div class="row justify-content-center">
		<div class="col-10">
			<%= render 'shared/errors', obj: @category %>
			<%= form_with(model: @category, class: "shadow p-3 mb-4 bg-info rounded", local: true) do |f| %>
				<div class="form-group row">
					<%= f.label :name, "Category name", class: "col-sm-2 mb-3 col-form-label text-light" %>
					<div class="col-sm-10">
						<%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a name" %>
					</div>
				</div>
				<div class="form-group row">
					<div class="col-sm-12 text-center">
						<%= f.submit class: "btn btn-outline-light btn-lg" %>
					</div>
				</div>
			<% end %>
		</div>
	</div>
</div>

<div class="container text-center pb-3">
	<%= link_to 'Cancel', categories_path, class: "text-info" %>
</div>

app/views/categories/show.html.erb
<h1 class="text-center pt-4 pb-4"><%= @category.name %></h1>

<div class="flickr_pagination pb-4">
	<%= will_paginate @articles, :container => false %>
</div>
<div class="container pb-4">
	<% @articles.each do |article| %>
		<%= render 'articles/article_card', article: article %>
	<% end %>
</div>
<div class="flickr_pagination pb-4">
	<%= will_paginate @articles, :container => false %>
</div>

app/views/layouts/_footer.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
</head>
<body>
	<footer class="text-center text-lg-start bg-dark text-white sticky-bottom">
		<div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
			<small>Copyright &copy; <%= link_to "Areesh Zindani", "https://areeshz.github.io", class: "text-white text-underline-hover" %></small>
		</div>
	</footer>
</body>
</html>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
	<div class="container">
		<div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
			<%= msg %>
			<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
		</div>
	</div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	<div class="container-fluid">
	<%= link_to "ALPHA BLOG", root_path, class: "navbar-brand", id: "logo" %>
	<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav me-auto mb-2 mb-lg-0">
			<li class="nav-item">
				<%= link_to "Bloggers", users_path, class: "nav-link" %>
			</li>
			<li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
					Articles
				</a>
				<ul class="dropdown-menu" aria-labelledby="navbarDropdown">
					<li><%= link_to "All Articles", articles_path, class: "dropdown-item" %></li>
					<% if logged_in? %>
						<li><hr class="dropdown-divider"></li>
						<li><%= link_to "New Article", new_article_path, class: "dropdown-item" %></li>
					<% end %>
				</ul>
			</li>
			<li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
					Categories
				</a>
				<ul class="dropdown-menu" aria-labelledby="navbarDropdown">
					<li><%= link_to "View Categories", categories_path, class: "dropdown-item" %></li>
					<% if logged_in? && current_user.admin? %>
						<li><hr class="dropdown-divider"></li>
						<li><%= link_to "New Category", new_category_path, class: "dropdown-item" %></li>
					<% end %>
				</ul>
			</li>
			<li class="nav-item">
				<%= link_to "About", about_path, class: "nav-link" %>
			</li>
		</ul>
		<ul class="navbar-nav ml-auto">
			<% if logged_in? %>
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
						<%= "(Admin) " if current_user.admin?%><%= current_user.username %>
					</a>
					<ul class="dropdown-menu" aria-labelledby="navbarDropdown">
						<%= link_to "View Profile", user_path(current_user), class: "dropdown-item" %>
						<%= link_to "Edit Profile", edit_user_path(current_user), class: "dropdown-item" %>
						<%= link_to "Delete Account", user_path(current_user), method: :delete, data: { confirm: "Are you sure you want to delete your account?" }, class: "dropdown-item text-danger" %>
					</ul>
				</li>
				<li class="nav-item">
					<%= link_to "Logout", logout_path, method: :delete, class: "nav-link" %>
				</li>
			<% else %>
				<li class="nav-item">
					<%= link_to "Sign Up", signup_path, class: "nav-link" %>
				</li>
				<li class="nav-item">
					<%= link_to "Login", login_path, class: "nav-link" %>
				</li>
			<% end %>
		</ul>
	</div>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>AlphaBlog</title>
		<meta name="viewport" content="width=device-width,initial-scale=1">
		<%= csrf_meta_tags %>
		<%= csp_meta_tag %>

		<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
	</head>

	<body>
		<%= render 'layouts/navbar' %>

		<div id="page-content">
			<%= render 'layouts/messages' %> <!-- unlike the edit.html.erb file, we DO need to specify the folder name here (i.e. 'layouts/messages') -->
			<%= yield %>
		</div>

		<%= render 'layouts/footer' %>
	</body>
</html>

app/views/pages/about.html.erb
<h1>This is the about page for alpha-blog</h1>
<%= link_to 'Home', root_path %> |
<%= link_to 'Articles List', articles_path %>
<h2>These tags were generated automatically using emmet</h2>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>Document</title>
	</head>
	<body>
		<style type="text/css">
			.jumbotron {
				padding: 4rem 2rem;
				margin-bottom: 2rem;
				background-color: gray;
				border-radius: .3rem;
			}
		</style>
		<div class="container pt-4 vh-100">
			<div class="jumbotron text-center text-light">
				<h1 class="display-4">Alpha Blog</h1>
				<p class="lead">Sign up today!</p>
				<hr class="my-4">
				<p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
				<%= link_to "Sign Up!", signup_path, class: "btn btn-success btn-lg" %>
			</div>
		</div>
	</body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
	<div class="alert alert-danger alert-dismissible fade show" role="alert">
		<h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
		<ul>
			<% obj.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
		<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
	</div>
<% end %>

app/views/users/_form.html.erb
<div class="container">
	<div class="row justify-content-center">
		<div class="col-10">
			<%= render 'shared/errors', obj: @user %>
			<%= form_with(model: @user, class: "shadow p-3 mb-4 bg-info rounded", local: true) do |f| %>
				<div class="form-group row">
					<%= f.label :username, class: "col-sm-2 mb-3 col-form-label text-light" %>
					<div class="col-sm-10">
						<%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Enter a username" %>
					</div>
				</div>
				<div class="form-group row">
					<%= f.label :email, class: "col-sm-2 mb-3 col-form-label text-light" %>
					<div class="col-sm-10">
						<%= f.email_field :email, class: "form-control shadow rounded", placeholder: "janedoe@example.com" %>
					</div>
				</div>
				<div class="form-group row">
					<%= f.label :password, class: "col-sm-2 mb-3 col-form-label text-light" %>
					<div class="col-sm-10">
						<%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Choose a password" %>
					</div>
				</div>
				<div class="form-group row">
					<div class="col-sm-12 text-center">
						<%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-outline-light btn-lg") %>
					</div>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/users/_user_card.html.erb
<div class="row justify-content-md-center">
	<div class="col-8 pb-4">
		<div class="card text-center shadow mb-5 bg-white rounded">
			<div class="card-header fst-italic">
				<%= link_to user.username, user_path(user), class: "text-underline-hover" %>
			</div>
			<div class="card-body">
				<%= gravatar_for user, size: 150 %>
				<p class="mb-3 mt-3"><%= pluralize(user.articles.length, "article") %></p>
				<%= link_to "View Profile", user_path(user), class: "btn btn-outline-success" %>
				<% if logged_in? && user == current_user %>
					<%= link_to "Edit Profile", edit_user_path(user), class: "btn btn-outline-info" %>
				<% end %>
				<% if logged_in? && current_user.admin? %>
					<%= link_to "Delete Account", user_path(user), method: :delete, class: "btn btn-outline-danger", data: { confirm: "Are you sure you want to delete this account and all associated articles?" } %>
				<% end %>
			</div>
			<div class="card-footer text-muted">
				<small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
			</div>
		</div>
	</div>
</div>

app/views/users/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
</head>
<body>
	<h1 class="text-center pt-4 pb-4">Edit your profile</h1>

	<%= render 'form' %>
</body>
</html>

app/views/users/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
</head>
<body>
	<h1 class="text-center pt-4 pb-4">Alpha Bloggers</h1>
	<div class="flickr_pagination pb-4">
		<%= will_paginate @users, :container => false %>
	</div>
	<div class="container pb-4">
		<% @users.each do |user| %>
			<%= render 'user_card', user: user %>
		<% end %>
	</div>
	<div class="flickr_pagination pb-4">
		<%= will_paginate @users, :container => false %>
	</div>
</body>
</html>

app/views/users/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
</head>
<body>
	<h1 class="text-center pt-4 pb-4">Sign up for Alpha Blog</h1>

	<%= render 'form' %>
</body>
</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
</head>
<body>
	<h1 class="text-center pt-4 pb-4"><%= @user.username %>'s Profile</h1>
	<%= gravatar_for @user, size: 200 %>
	<div class="text-center mt-4">
		<% if logged_in? && @user == current_user %>
			<%= link_to "Edit Your Profile", edit_user_path(@user), class: "btn btn-outline-info" %>
		<% end %>
	</div>
	<h3 class="text-center pt-4 pb-4">Articles</h3>
	<div class="flickr_pagination pb-4">
		<%= will_paginate @articles, :container => false %>
	</div>
	<div class="container pb-4">
		<% @articles.each do |article| %>
			<%= render 'articles/article_card', article: article %>
		<% end %>
	</div>
	<div class="flickr_pagination pb-4">
		<%= will_paginate @articles, :container => false %>
	</div>
</body>
</html>